from app import app
from flask import render_template, redirect, url_for

#home page
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/games')
def games():
    game_list=[{'title':'Portal 2', 'description':'The single-player portion of Portal 2 introduces a cast of dynamic new characters, a host of fresh puzzle elements, and a much larger set of devious test chambers. Players will explore never-before-seen areas of the Aperture Science Labs and be reunited with GLaDOS, the occasionally murderous computer companion who guided them through the original game.','link':'https://store.steampowered.com/app/620/Portal_2/','image':'../static/photos/Portal2cover.jpg'},{'title':'Sid Meiers Civilization V', 'description':'Become Ruler of the World by establishing and leading a civilization from the dawn of man into the space age: Wage war, conduct diplomacy, discover new technologies, go head-to-head with some of history’s greatest leaders and build the most powerful empire the world has ever known.','link':'https://store.steampowered.com/app/8930/Sid_Meiers_Civilization_V/','image':'../static/photos/civ_picture.jpg'},{'title':'Europa Universalis 4', 'description':'Paradox Development Studio is back with the fourth installment of the award-winning Europa Universalis series. This classic grand strategy game gives you control of a nation through four dramatic centuries. Rule your land and dominate the world with unparalleled freedom, depth and historical accuracy. Write a new history of the world and build an empire for the ages.','link':'https://store.steampowered.com/app/236850/Europa_Universalis_IV/','image':'../static/photos/eu4_pic.png'},{'title':'Factorio', 'description':'Factorio is a game in which you build and maintain factories. You will be mining resources, researching technologies, building infrastructure, automating production and fighting enemies. In the beginning you will find yourself chopping trees, mining ores and crafting mechanical arms and transport belts by hand, but in short time you can become an industrial powerhouse, with huge solar fields, oil refining and cracking, manufacture and deployment of construction and logistic robots, all for your resource needs. However this heavy exploitation of the planet\'s resources does not sit nicely with the locals, so you will have to be prepared to defend yourself and your machine empire.','link':'https://store.steampowered.com/app/427520/Factorio/','image':'../static/photos/factorio_pic.jpg'},{'title':'The Henry Stickmin Collection', 'description':'The Henry Stickmin Collection is a Newgrounds choose-your-own-path classic, reborn and revitalized. This 6-game epic culminates in multiple entirely canon, extremely different endings. Each step of the journey has you choose from options such as a Teleporter or calling in your buddy Charles to help you out. Correct choices will move the story forward, but incorrect choices lead to a fail. If you get to the end on your first try, you\'re doing it wrong. Failing is half the fun.','link':'https://store.steampowered.com/app/1089980/The_Henry_Stickmin_Collection/','image':'../static/photos/stickmin_pic.jpg'}]
    return render_template('games.html', game_list=game_list)